### ISSUE TITLE
Not able to access serial port from docker

### ISSUE THREAD

**Issue by jonfrank** [mak3r/micropython-esp32-dev#1]
This is exactly what I was looking for - thanks @mak3r for putting it together. 

I'm having trouble though: despite the `--privileged -v /dev:/dev` switches, I'm unable to connect to the serial port from the running docker image. I get:
```
serial.serialutil.SerialException: [Errno 21] could not open port /dev/cu.usbserial-55D6A5B0AB: [Errno 21] Is a directory: '/dev/cu.usbserial-55D6A5B0AB' 
```
Any suggestions? I'm able to upload compiled code to the device (M5stickC-plus) from the Arduino app OK, and also access through a terminal emulator works fine, so it seems that the port is working. I'm on a Mac. Any suggestions?

**Comment by mak3r** [comment]
@jonfrank docker devices don't work on a Mac because (Docker Desktop / Docker for Mac) runs in a hypervisor which is not configured to passthru devices. Check out the docker [FAQ](https://docs.docker.com/desktop/faqs/#can-i-pass-through-a-usb-device-to-a-container) on this. 

You could manage the hypervisor yourself, setup device pathru to guest machines, install a linux vm and docker and it should work. You could also mount your code in the vm so it is still local code but generally keeps your mac free of the build cruft. It doesn't sound as elegant however, this is ultimately what Docker Desktop is doing for you but with less control given back to the end user.
